# Numpy Refresher

In [13]:
import numpy as np

In [2]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]

In [5]:
np_height = np.array(height)
np_weight = np.array(weight)

bmi = np_weight/np_height **2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

#### adding in list vs adding in numpy

In [7]:
list_one = [1,2,3]
list_one + list_one # this will add the lists together, not the actual elements

[1, 2, 3, 1, 2, 3]

In [9]:
np_array = np.array([1,2,3])
np_array + np_array # numpy adds the actual elements together (1+1)(2+2)(3+3) --> [2,4,6]

array([2, 4, 6])

In [12]:
bmi > 23 #returns boolean array
bmi[bmi>23] #returns values in bmi where the bmi is greater than 23

array([24.7473475])

###### Create np_height_in from np_baseball
    np_height_in = np_baseball[:,0] #this code will assign all the values of the first column to the numpy array

###### Print out the mean of np_height_in
    print(np.mean(np_height_in)) #print the mean

###### Print out the median of np_height_in
    print(np.median(np_height_in)) #print the median

In [14]:
positions = ['GK', 'M', 'F', 'D', 'GK', 'M', 'F', 'F', 'GK', 'D']
heights = [191, 184, 185, 180, 195, 177, 183, 183, 193, 175]

# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = np.array(positions)
np_heights = np.array(heights)

# Heights of the goalkeepers: gk_heights
gk_heights = np_heights[np_positions=='GK']

# Heights of the other players: other_heights
other_heights = np_heights[np_positions!='GK']

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

Median height of goalkeepers: 193.0
Median height of other players: 183.0
